[
  {
    business_status: 'OPERATIONAL',
    geometry: {location: [Object], viewport: [Object]},
    name: '동원칼국수',
    photos: [[Object]],
    place_id: 'ChIJy5xGrdBLZTUR25oVgKVv9_c',
    rating: 3.8,
    vicinity: '11 Cheongsaseo-ro 54beon-gil, Seo-gu',
  },
  {
    business_status: 'OPERATIONAL',
    geometry: {location: [Object], viewport: [Object]},
    name: 'Daeseon Kalguksu',
    photos: [[Object]],
    place_id: 'ChIJ9ZlESmdJZTURbHRSfCB-38s',
    rating: 4.1,
    vicinity: 'Seo-gu, Dunsanjung-ro 40beon-gil, 28 오성빌딩 2층',
  },
  {
    business_status: 'OPERATIONAL',
    geometry: {location: [Object], viewport: [Object]},
    name: '대흥동칼국수',
    photos: [[Object]],
    place_id: 'ChIJhZuNaelLZTURsqAshO2HpJc',
    rating: 4.2,
    vicinity: '292-17 Galma-dong, Seo-gu',
  },
  {
    business_status: 'OPERATIONAL',
    geometry: {location: [Object], viewport: [Object]},
    name: 'Mug-Eunjeong',
    photos: [[Object]],
    place_id: 'ChIJzRrx-hFLZTURwEO3g9sB-v4',
    rating: 4.2,
    vicinity: '1209 Dunsan-dong, Seo-gu',
  },
  {
    business_status: 'OPERATIONAL',
    geometry: {location: [Object], viewport: [Object]},
    name: '홍사골칼국수 본점',
    photos: [[Object]],
    place_id: 'ChIJBdqxg6JLZTURjAt6XJHm74M',
    rating: 4.7,
    vicinity: '630 탄방동 Seo-gu',
  },
  {
    business_status: 'OPERATIONAL',
    geometry: {location: [Object], viewport: [Object]},
    name: '대선칼국수 갤러리아백화점 타임월드점',
    photos: [[Object]],
    place_id: 'ChIJ-_73oOBLZTURng_EjrkpuU8',
    rating: 3,
    vicinity: '둔산동 1036번지 서구 대전광역시 KR',
  },
];
